version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      # Switch between SQLite (default) or MySQL by changing DB_CONNECTION
      DB_CONNECTION: sqlite
      # Uncomment these lines if you enable the db service below
      # DB_HOST: db
      # DB_PORT: 3306
      # DB_DATABASE: laravel
      # DB_USERNAME: laravel
      # DB_PASSWORD: laravel
    depends_on:
      - db

  # Optional MySQL database – remove or comment out if you want pure SQLite
  db:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
